[2023-10-22T05:10:55.429+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T05:10:53.335493+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T05:10:55.450+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T05:10:53.335493+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T05:10:55.474+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T05:10:53.335493+00:00 [queued]>
[2023-10-22T05:10:55.481+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T05:10:53.335493+00:00 [queued]>
[2023-10-22T05:10:55.482+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T05:10:55.493+0000] {taskinstance.py:1382} INFO - Executing <Task(NhlStatsSaveOperator): save_nhl_stats> on 2023-10-22 05:10:53.335493+00:00
[2023-10-22T05:10:55.499+0000] {standard_task_runner.py:57} INFO - Started process 9240 to run task
[2023-10-22T05:10:55.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nhl_stats_save', 'save_nhl_stats', 'manual__2023-10-22T05:10:53.335493+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/nhl_stats_save.py', '--cfg-path', '/tmp/tmpwm454apq']
[2023-10-22T05:10:55.502+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask save_nhl_stats
[2023-10-22T05:10:55.512+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-22T05:10:55.539+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T05:10:53.335493+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T05:10:55.541+0000] {task_command.py:416} INFO - Running <TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T05:10:53.335493+00:00 [running]> on host 9b9e466d03cf
[2023-10-22T05:10:55.599+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='nhl_stats_save' AIRFLOW_CTX_TASK_ID='save_nhl_stats' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T05:10:53.335493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T05:10:53.335493+00:00'
[2023-10-22T05:10:55.959+0000] {logging_mixin.py:151} INFO - --------
[2023-10-22T05:10:55.960+0000] {logging_mixin.py:151} INFO - {'gamesPlayed': 5, 'wins': 5, 'losses': 0, 'ot': 0, 'pts': 10, 'ptPctg': '100.0', 'goalsPerGame': 4.0, 'goalsAgainstPerGame': 1.6, 'evGGARatio': 1.2857, 'powerPlayPercentage': '27.8', 'powerPlayGoals': 5.0, 'powerPlayGoalsAgainst': 1.0, 'powerPlayOpportunities': 18.0, 'penaltyKillPercentage': '95.5', 'shotsPerGame': 37.2, 'shotsAllowed': 28.0, 'winScoreFirst': 1.0, 'winOppScoreFirst': 1.0, 'winLeadFirstPer': 1.0, 'winLeadSecondPer': 1.0, 'winOutshootOpp': 1.0, 'winOutshotByOpp': 1.0, 'faceOffsTaken': 305.0, 'faceOffsWon': 144.0, 'faceOffsLost': 161.0, 'faceOffWinPercentage': '47.2', 'shootingPctg': 10.8, 'savePctg': 0.943}
[2023-10-22T05:10:55.960+0000] {logging_mixin.py:151} INFO - --------
[2023-10-22T05:10:55.961+0000] {logging_mixin.py:151} INFO - {'wins': '2nd', 'losses': '2nd', 'ot': '15th', 'pts': '2nd', 'ptPctg': '2nd', 'goalsPerGame': '6th', 'goalsAgainstPerGame': '2nd', 'evGGARatio': '14th', 'powerPlayPercentage': '9th', 'powerPlayGoals': '9th', 'powerPlayGoalsAgainst': '3rd', 'powerPlayOpportunities': '11th', 'penaltyKillOpportunities': '28th', 'penaltyKillPercentage': '3rd', 'shotsPerGame': '2nd', 'shotsAllowed': '7th', 'winScoreFirst': '6th', 'winOppScoreFirst': '2nd', 'winLeadFirstPer': '8th', 'winLeadSecondPer': '3rd', 'winOutshootOpp': '5th', 'winOutshotByOpp': '5th', 'faceOffsTaken': '10th', 'faceOffsWon': '13th', 'faceOffsLost': '28th', 'faceOffWinPercentage': '24th', 'savePctRank': '2nd', 'shootingPctRank': '11th'}
[2023-10-22T05:10:55.961+0000] {logging_mixin.py:151} INFO - Вставка team:[{'uid': 'aa412713-ab76-4bd6-aaad-cc6cda668184', 'id': 21}]
[2023-10-22T05:10:55.962+0000] {logging_mixin.py:151} INFO - Вставка stats:[{'team_uid': 'aa412713-ab76-4bd6-aaad-cc6cda668184', 'uid': 'f4e33f07-8f15-4483-b3b1-bf82fb73f8c1', 'display_name': 'statsSingleSeason', 'game_type': {'id': 'R', 'description': 'Regular season', 'postseason': False}}, {'team_uid': 'aa412713-ab76-4bd6-aaad-cc6cda668184', 'uid': 'f5980851-13aa-4822-8543-f2e00b07a04e', 'display_name': 'regularSeasonStatRankings', 'game_type': None}]
[2023-10-22T05:10:55.962+0000] {logging_mixin.py:151} INFO - Вставка splits:[{'stat_uid': 'f4e33f07-8f15-4483-b3b1-bf82fb73f8c1', 'uid': '822b0c7c-646b-42e3-aabb-4623f55bc2af'}, {'stat_uid': 'f5980851-13aa-4822-8543-f2e00b07a04e', 'uid': 'f52c4b3e-0719-4ada-999a-540b3faf1ec1'}]
[2023-10-22T05:10:55.962+0000] {logging_mixin.py:151} INFO - postgresql+psycopg2://db_homework:db_homework@192.168.1.113:5434/db_homework
[2023-10-22T05:10:56.043+0000] {migration.py:213} INFO - Context impl PostgresqlImpl.
[2023-10-22T05:10:56.044+0000] {migration.py:216} INFO - Will assume transactional DDL.
[2023-10-22T05:10:56.045+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 120, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 88, in save_data
    table.insert_many(rows=stats, chunk_size=10000)
  File "/home/airflow/.local/lib/python3.10/site-packages/dataset/table.py", line 172, in insert_many
    self._sync_columns(sync_row, ensure, types=types)
  File "/home/airflow/.local/lib/python3.10/site-packages/dataset/table.py", line 380, in _sync_columns
    self._sync_table(sync_columns.values())
  File "/home/airflow/.local/lib/python3.10/site-packages/dataset/table.py", line 355, in _sync_table
    self.db.op.add_column(self.name, column, self.db.schema)
TypeError: add_column() takes 3 positional arguments but 4 were given
[2023-10-22T05:10:56.051+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=nhl_stats_save, task_id=save_nhl_stats, execution_date=20231022T051053, start_date=20231022T051055, end_date=20231022T051056
[2023-10-22T05:10:56.061+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task save_nhl_stats (add_column() takes 3 positional arguments but 4 were given; 9240)
[2023-10-22T05:10:56.075+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T05:10:56.092+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
