[2023-10-22T06:28:46.177+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:28:44.600684+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:28:46.198+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:28:44.600684+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:28:46.220+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:28:44.600684+00:00 [queued]>
[2023-10-22T06:28:46.227+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:28:44.600684+00:00 [queued]>
[2023-10-22T06:28:46.228+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T06:28:46.238+0000] {taskinstance.py:1382} INFO - Executing <Task(NhlStatsSaveOperator): save_nhl_stats> on 2023-10-22 06:28:44.600684+00:00
[2023-10-22T06:28:46.244+0000] {standard_task_runner.py:57} INFO - Started process 1573 to run task
[2023-10-22T06:28:46.247+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nhl_stats_save', 'save_nhl_stats', 'manual__2023-10-22T06:28:44.600684+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/nhl_stats_save.py', '--cfg-path', '/tmp/tmpo193u8tz']
[2023-10-22T06:28:46.249+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask save_nhl_stats
[2023-10-22T06:28:46.261+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-22T06:28:46.286+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:28:44.600684+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:28:46.288+0000] {task_command.py:416} INFO - Running <TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:28:44.600684+00:00 [running]> on host 06f8d34233ae
[2023-10-22T06:28:46.421+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='nhl_stats_save' AIRFLOW_CTX_TASK_ID='save_nhl_stats' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T06:28:44.600684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T06:28:44.600684+00:00'
[2023-10-22T06:28:46.992+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 101, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 74, in save_data
    (team, stats, splits) = self.parse_data(df)
  File "/opt/airflow/plugins/nhl_stats_save_operator.py", line 38, in parse_data
    'games_played': jsSplit.get('stat')['gamesPlayed'],
KeyError: 'gamesPlayed'
[2023-10-22T06:28:47.000+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=nhl_stats_save, task_id=save_nhl_stats, execution_date=20231022T062844, start_date=20231022T062846, end_date=20231022T062847
[2023-10-22T06:28:47.011+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task save_nhl_stats ('gamesPlayed'; 1573)
[2023-10-22T06:28:47.021+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T06:28:47.038+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
