[2023-10-21T11:09:10.861+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=random_cannabis_save/run_id=manual__2023-10-21T11:09:08.272886+00:00/task_id=get_random_cannabis permission to 509
[2023-10-21T11:09:10.896+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=random_cannabis_save/run_id=manual__2023-10-21T11:09:08.272886+00:00/task_id=get_random_cannabis permission to 509
[2023-10-21T11:09:10.934+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_cannabis_save.get_random_cannabis manual__2023-10-21T11:09:08.272886+00:00 [queued]>
[2023-10-21T11:09:10.948+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_cannabis_save.get_random_cannabis manual__2023-10-21T11:09:08.272886+00:00 [queued]>
[2023-10-21T11:09:10.949+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-21T11:09:10.967+0000] {taskinstance.py:1382} INFO - Executing <Task(RandomCannabisOperator): get_random_cannabis> on 2023-10-21 11:09:08.272886+00:00
[2023-10-21T11:09:10.976+0000] {standard_task_runner.py:57} INFO - Started process 156 to run task
[2023-10-21T11:09:10.979+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'random_cannabis_save', 'get_random_cannabis', 'manual__2023-10-21T11:09:08.272886+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/random_cannabis_save.py', '--cfg-path', '/tmp/tmp3w3xlamk']
[2023-10-21T11:09:10.981+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask get_random_cannabis
[2023-10-21T11:09:10.998+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-21T11:09:11.040+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=random_cannabis_save/run_id=manual__2023-10-21T11:09:08.272886+00:00/task_id=get_random_cannabis permission to 509
[2023-10-21T11:09:11.044+0000] {task_command.py:416} INFO - Running <TaskInstance: random_cannabis_save.get_random_cannabis manual__2023-10-21T11:09:08.272886+00:00 [running]> on host 1646a4c502fb
[2023-10-21T11:09:11.134+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='random_cannabis_save' AIRFLOW_CTX_TASK_ID='get_random_cannabis' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T11:09:08.272886+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-21T11:09:08.272886+00:00'
[2023-10-21T11:09:12.141+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/random_cannabis_operator.py", line 43, in execute
    self.save_data(data)
  File "/opt/airflow/plugins/random_cannabis_operator.py", line 19, in save_data
    print(pg_hook.get_url())
AttributeError: 'PostgresHook' object has no attribute 'get_url'. Did you mean: 'get_uri'?
[2023-10-21T11:09:12.160+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=random_cannabis_save, task_id=get_random_cannabis, execution_date=20231021T110908, start_date=20231021T110910, end_date=20231021T110912
[2023-10-21T11:09:12.180+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task get_random_cannabis ('PostgresHook' object has no attribute 'get_url'; 156)
[2023-10-21T11:09:12.198+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-21T11:09:12.330+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
