[2023-10-22T06:44:53.575+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:44:50.940119+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:44:53.606+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:44:50.940119+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:44:53.630+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:44:50.940119+00:00 [queued]>
[2023-10-22T06:44:53.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:44:50.940119+00:00 [queued]>
[2023-10-22T06:44:53.638+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T06:44:53.649+0000] {taskinstance.py:1382} INFO - Executing <Task(NhlStatsSaveOperator): save_nhl_stats> on 2023-10-22 06:44:50.940119+00:00
[2023-10-22T06:44:53.655+0000] {standard_task_runner.py:57} INFO - Started process 2170 to run task
[2023-10-22T06:44:53.657+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nhl_stats_save', 'save_nhl_stats', 'manual__2023-10-22T06:44:50.940119+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/nhl_stats_save.py', '--cfg-path', '/tmp/tmphj9nxkh5']
[2023-10-22T06:44:53.659+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask save_nhl_stats
[2023-10-22T06:44:53.668+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-22T06:44:53.691+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=nhl_stats_save/run_id=manual__2023-10-22T06:44:50.940119+00:00/task_id=save_nhl_stats permission to 509
[2023-10-22T06:44:53.693+0000] {task_command.py:416} INFO - Running <TaskInstance: nhl_stats_save.save_nhl_stats manual__2023-10-22T06:44:50.940119+00:00 [running]> on host 06f8d34233ae
[2023-10-22T06:44:53.752+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='babintseva' AIRFLOW_CTX_DAG_ID='nhl_stats_save' AIRFLOW_CTX_TASK_ID='save_nhl_stats' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T06:44:50.940119+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T06:44:50.940119+00:00'
[2023-10-22T06:44:53.753+0000] {taskinstance.py:1937} ERROR - Task failed with exception
TypeError: NhlStatsSaveOperator.execute() got an unexpected keyword argument 'context'
[2023-10-22T06:44:53.759+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=nhl_stats_save, task_id=save_nhl_stats, execution_date=20231022T064450, start_date=20231022T064453, end_date=20231022T064453
[2023-10-22T06:44:53.769+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task save_nhl_stats (NhlStatsSaveOperator.execute() got an unexpected keyword argument 'context'; 2170)
[2023-10-22T06:44:53.789+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T06:44:53.807+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
